cliente=input("Digite o nome do cliente: ")
vencimento=input("Digite o dia de vencimento: ")
mes_do_vencimento=input("Digite o mês de vencimento: ")
valor_da_fatura=input("Digite o valor da fatura: ")
print(f"Olá, {cliente} ")
print(f"A sua fatura com vencimento em {vencimento} de {mes_do_vencimento} no valor de R$ {valor_da_fatura} está fechada." )